### ISSUE TITLE
Input regex matches non-alpha characters

### ISSUE THREAD

**Issue by wlthomson** [CarlosNZ/Word-Wheel-Solver#3]
Nice tool!

Minor bug in current regex: `^[A-z?]$` matches all ASCII symbols from `65 (A)` to `122 (z)` inclusive. This includes some non-alpha symbols: `[`, `\`,`]`, `^`, `_`, `` ` ``.

First solution that comes to mind is to convert to upper-case before regex checking, then can just do a simple capital letter regex?

**Comment by CarlosNZ** [comment]
Ah, good catch, I thought `[A-z]` was letters only.

> First solution that comes to mind is to convert to upper-case before regex checking, then can just do a simple capital letter regex?

The dictionary is all lower-case, so I was keeping the actual values all lower-case and only using Upper for display. I mean, I guess the dictionary could be all UPPER...

**Comment by CarlosNZ** [comment]
Done in v0.5
